### ISSUE TITLE
Custom Envoy

### ISSUE THREAD

**Issue by donovano** [aws/aws-app-mesh-examples#104]
Will it be possible to deploy to App Mesh a custom built Envoy binary that is compatible with App Mesh of course e.g. with SigV4 etc? Custom filters for Envoy require a custom Envoy.

**Comment by jamsajones** [comment]
Yes you can bring your own Envoy as long as it includes SigV4 authentication. However our SigV4 implementation in Envoy's github has not been merged yet. 

You can build in custom filters into Envoy but they will only work if they are configured via static bootstrap config. We are planning custom filters as a feature and would appreciate your feedback on our roadmap item #36.
