### ISSUE TITLE
Create an example tutorial for service discovery

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-examples#117]
Create a new example tutorial that focuses just on service discovery in AWS App Mesh.

**Comment by sviik** [comment]
+1

Service discovery was the most confusing part for me when starting with App Mesh.

**Comment by kiranmeduri** [comment]
Do these walkthroughs address this concern?

- ECS: https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-servicediscovery-cloudmap
- Kubernetes: https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-k8s-cloudmap

**Comment by avinashetrx** [comment]
These walkthrough works but wanted to start without using cloudmap, We wanted to used dns mode of service discovery. Also I have question about listener rules used for databases, Will those be using tcp or http ?

**Comment by kiranmeduri** [comment]
> These walkthrough works but wanted to start without using cloudmap, We wanted to used dns mode of service discovery. Also I have question about listener rules used for databases, Will those be using tcp or http ?

- https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-alb shows how to use virtual-node with DNS. 

- To use databases you most-likely will need a TCP rule. However, note that mysql databases have a blocking bug that is being worked on. See https://github.com/aws/aws-app-mesh-roadmap/issues/62

**Comment by efe-selcuk** [comment]
Closing as we have some walkthroughs linked for service discovery
