### ISSUE TITLE
Create an example tutorial for observability (logging, metrics, tracing)

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-examples#120]
Create an example tutorial that focuses on observability features and integrations with App Mesh

**Comment by mhausenblas** [comment]
Yup, I'm working on exactly this (for EKS) in the walkthroughs directory.

**Comment by chenrui333** [comment]
@mhausenblas that sounds very nice! When can we expect to see it?

**Comment by mhausenblas** [comment]
The basic walkthrough and CloudWatch is already available, X-Ray I hope very soon, maybe as early as this week. See https://github.com/mhausenblas/aws-app-mesh-examples/blob/master/walkthroughs/eks/README.md

**Comment by chenrui333** [comment]
nice, thanks for the update!

**Comment by Mic-U** [comment]
I'm looking forward to the example tutorial outputting metrics to CloudWatch Metrics.

**Comment by mhausenblas** [comment]
@Mic-U both CloudWatch and X-Ray (for App Mesh with EKS) are available.

**Comment by Mic-U** [comment]
I tried walkthrough of CloudWatch, then succeeded to put logs to CloudWatch Logs.
However, It seemed to not output metrics to CloudWatch Metrics.

https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/eks/o11y-cloudwatch.md

**Comment by rverma-nikiai** [comment]
We have 2 log files per application. We are using 2 sources in fluentd conf. Though I couldn't understand the significance of /dev/stdout since the fluentd.conf seems to get logs directly through /var/log/containers directory.

**Comment by dileep-p** [comment]
I'm looking forward to the example tutorial expose metrics endpoint to scrap from promethues..

**Comment by kiranmeduri** [comment]
#143 provides an example to publish metrics to AWS CloudWatch.

**Comment by stafot** [comment]
Is there a way to setup X-ray distributed tracing on EKS and App Mesh using App Mesh CRDs? I mean to set a label or an ENV to the `mesh.yaml` and no need to use `eksctl` or` aws cli` of app mesh to enable tracing?

**Comment by kiranmeduri** [comment]
> Is there a way to setup X-ray distributed tracing on EKS and App Mesh using App Mesh CRDs? I mean to set a label or an ENV to the `mesh.yaml` and no need to use `eksctl` or` aws cli` of app mesh to enable tracing?

Not CRD, but you can configure [aws-app-mesh-inject](https://github.com/aws/eks-charts/tree/master/stable/appmesh-inject) to enable tracing. Following will get you started.

```
helm upgrade -i appmesh-inject ./stable/appmesh-inject \ 
        --namespace appmesh-system \
        --set tracing.enabled=true \
        --set tracing.provider=x-ray
```
With that you will have every pod get both app-mesh-proxy (Envoy) and x-ray-daemon injected and configured appropriately.

**Comment by fawadkhaliq** [comment]
EKS + AppMesh + Prometheus example: https://github.com/aws/aws-app-mesh-examples/pull/337
EKS + AppMesh + Grafana example: https://github.com/aws/aws-app-mesh-examples/pull/338

**Comment by fawadkhaliq** [comment]
EKS + AppMesh + Jaeger example: https://github.com/aws/aws-app-mesh-examples/pull/357

**Comment by fawadkhaliq** [comment]
Added walkthroughs for Prometheus, Grafana and Jaeger
