### ISSUE TITLE
OAuth 2 integration example

### ISSUE THREAD

**Issue by chenrui333** [aws/aws-app-mesh-examples#131]
It would be good to have some OAuth 2 integration example (Google OAuth, Github, etc.) to expose the EKS workload publicly.

**Comment by kiranmeduri** [comment]
As of now App Mesh does not support [ingress-routing](https://github.com/aws/aws-app-mesh-roadmap/issues/37), so exposing workload publicly using App Mesh is not supported. It is possible to achieve this using [ALB](https://aws.amazon.com/blogs/aws/built-in-authentication-in-alb/) and [aws-alb-ingress-controller](https://github.com/kubernetes-sigs/aws-alb-ingress-controller). 

However, will you be interested in OAuth2 support between services within a mesh?

Thanks for posting.

**Comment by herrhound** [comment]
Resolving the old issue, as authorization is a roadmap item at the moment: https://github.com/aws/aws-app-mesh-roadmap/issues/140
