### ISSUE TITLE
ECS curl - 500 - Unexpected Error

### ISSUE THREAD

**Issue by mcheriyath** [aws/aws-app-mesh-examples#135]
This is applicable only for ECS sample.

In the Sample application the port is 8080

https://github.com/aws/aws-app-mesh-examples/blob/31692a778d062ca3ccbdfce1477407fa59764848/examples/apps/colorapp/src/colorteller/main.go#L12

But in task definition
https://github.com/aws/aws-app-mesh-examples/blob/31692a778d062ca3ccbdfce1477407fa59764848/examples/apps/colorapp/ecs/colorteller-base-task-def.json#L35-L36

Shouldn't this be 8080 as well?

**Comment by kiranmeduri** [comment]
default-port will be overridden by 9080 due to 
```
...
{
    "name": "SERVER_PORT",
    "value": "9080"
}
...
```

500 errors you are noticing may be due to something else. Can you check if you can curl any of the colorteller services directly.

**Comment by mcheriyath** [comment]
Using the default values, I am getting this 503 error. I think the application needs some re-writes. 

Will close this issue for now. Thank you.
