### ISSUE TITLE
Template validation errors when running ecs-colorapp.sh

### ISSUE THREAD

**Issue by qrobinson-starz** [aws/aws-app-mesh-examples#136]
**Describe the bug**
When trying to run the ecs-colorapp.sh script, I get the following errors:
`Unknown parameter in input: "proxyConfiguration", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory, tags, pidMode, ipcMode`

`Unknown parameter in containerDefinitions[0]: "dependsOn", must be one of: name, image, repositoryCredentials, cpu, memory, memoryReservation, links, portMappings, essential, entryPoint, command, environment, mountPoints, volumesFrom, linuxParameters, secrets, hostname, user, workingDirectory, disableNetworking, privileged, readonlyRootFilesystem, dnsServers, dnsSearchDomains, extraHosts, dockerSecurityOptions, interactive, pseudoTerminal, dockerLabels, ulimits, logConfiguration, healthCheck, systemControls`

Is there a way to work around this?
Thanks

**Platform**
MacOS
awscli-1.16.143
botocore-1.12.133

**To Reproduce**
1. define required environment variables
2. follow instructions up to running ecs-colorapp.sh

**Expected behavior**
The colorapp service should be deployed.

**Config files, and API responses**
Template validation error

**Additional context**

**Comment by lavignes** [comment]
My first guess is that your ECS models are out of date.

It looks like you are using a cli version from yesterday https://pypi.org/project/awscli/1.16.143/

Can you double-check that you don't have an outdated model for ECS in `~/.aws/models/` that you may have added with https://docs.aws.amazon.com/cli/latest/reference/configure/add-model.html

**Comment by efe-selcuk** [comment]
Hey there. I just went through the steps to verify and I was able to provision the tasks with a CLI on 1.16.140, the latest version currently available on homebrew.

That error message is the client-side validation in the CLI, which suggests the model in the version that's being invoked during the calls to ECS is out of date. `proxyConfiguration` was added to the ECS API a while ago, but I see you've listed a very new version of the CLI.

Could you confirm that you don't have multiple versions of the CLI installed, or maybe have overridden a model? It's possible that you have a separate one installed (for example through homebrew), and that's the one that's being invoked by default in the scripts.

**Comment by qrobinson-starz** [comment]
Thanks for the response guys. I ended up uninstalling the cli and pulling it down from homebrew based on @efe-selcuk's suggestion and it seems to be working fine now.
