### ISSUE TITLE
Question: What is APPMESH_XDS_ENDPOINT used for?

### ISSUE THREAD

**Issue by uhef** [aws/aws-app-mesh-examples#138]
I'm confused about the environment variable `APPMESH_XDS_ENDPOINT` passed to the Envoy container. There doesn't seem to be any mention of this in AWS documentation: https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html

**Comment by bcelenza** [comment]
Hey @uhef, the `APPMESH_XDS_ENDPOINT` is used to specify an alternate address to connect to App Mesh's Envoy Management Service (an implementation of [Aggregate Discovery Service](https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/v2_overview#aggregated-discovery-service)). 

You do not need to specify anything for this environment variable. If nothing is passed, it will use the default address for the region you're running Envoy in.

We maintain this environment variable for anyone who may want to override this in the future (for example, if we release Envoy Management Service as an open-source project, https://github.com/aws/aws-app-mesh-roadmap/issues/42). We also use it internally to test our pre-production endpoints.

Hope that helps!
