### ISSUE TITLE
[Question] Load balancing ecs service multiple tasks with app mesh

### ISSUE THREAD

**Issue by shashanktomar** [aws/aws-app-mesh-examples#158]
We are trying out app-mesh. Our solution looks like the following:

`
Mesh Ingress (ALB) -> Service A -> Service B -> Mesh Egress -> External Service
`

In this setup, Service A and Service B are running over fargate with desired-count of 2 for each. These ECS services have cloud-map configuration enabled. We have verified that the traffic flows through envoy sidecar for both Service A and Service B.

When we hit ALB for ingress, the traffic is load-balanced for Service A by the ALB but the traffic from Service A always hit the same single task in Service B. We are unable to load balance traffic from Service A envoy proxy to Service B. Following is our understanding of the problem so far:
- As each service has multiple tasks running, all of the tasks get registered to Cloud Map service registry under the same DNS name
- This creates a couple of DNS A Records in Route 53 per service. It's worth mentioning that the ECS Service Discovery Options always creates a multi-value DNS record in Route53 if you don't select an existing service discovery name.
- We can see in envoy admin config dump for Serice A, that the cluster config dump for Service B has LOGICAL_DNS as type
- Now when Service A envoy proxy receives an egress request for Service B, it resolves the DNS from Route53 to the first IP in the list (as documented in LOGICAL_DNS config in envoy documents). This single IP of Task-1 is always targeted for outgoing request because of which the Task-2 for Service B never receives a request.

It will be helpful to understand why is it not working for us and also to get some idea about recommended practices around this pattern.

**Comment by efe-selcuk** [comment]
Closing in favor of https://github.com/aws/aws-app-mesh-roadmap/issues/70
