### ISSUE TITLE
Create an example of CI/CD via CodeSuite for AppMesh constructs

### ISSUE THREAD

**Issue by ashishgore** [aws/aws-app-mesh-examples#167]
Create an example of CI/CD via CodeSuite for AppMesh constructs

**Comment by subfuzion** [comment]
Hi @ashishgore, I agree it would be good to have some content on this added to the repo. In the meantime, I can point you out to the EKS Workshop created by my colleague, Brent Langston (@brentley) for starters.

https://eksworkshop.com/
(https://eksworkshop.com/servicemesh_with_appmesh/)
(https://eksworkshop.com/codepipeline/)

**Comment by brentley** [comment]
thanks @subfuzion! This would be a cool addition to eksworkshop.com if you're interested in working on the project... otherwise, I'll put it in our backlog also.

**Comment by herrhound** [comment]
Resolving the old issue as it doesn't generate enough interest. Please feel free to reopen it.
