### ISSUE TITLE
Remove external Docker repository references from examples

### ISSUE THREAD

**Issue by lavignes** [aws/aws-app-mesh-examples#191]
The Cloud Map How-To references external builds of the color apps and Envoy proxy:

* https://github.com/aws/aws-app-mesh-examples/blob/e3ad4d7754dbc317faceafd9189da47b67bbf154/walkthroughs/howto-servicediscovery-cloudmap/app.yaml#L216
* https://github.com/aws/aws-app-mesh-examples/blob/e3ad4d7754dbc317faceafd9189da47b67bbf154/walkthroughs/howto-servicediscovery-cloudmap/app.yaml#L192

I don't think we should be doing this long-term since it references images we or a customer cannot easily update or control.

We should be following the other examples and having the demo push images to a personal ECR repository.

**Comment by kiranmeduri** [comment]
#183 updates the images references
