### ISSUE TITLE
[BUG] Links in walkthroughs/eks are out of date

### ISSUE THREAD

**Issue by shubharao** [aws/aws-app-mesh-examples#223]
_**Important note on security disclosures**: If you think you’ve found a potential security issue, please do not post it in the Issues.  Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com)._

**Describe the bug**
I followed the instructions in https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/eks/base.md which installed older versions of controller and sidecar inject. This writeup needs updates or it can be deleted if all workflows are covered in any other https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-k8s-cloudmap

**Platform**
EKS etc.

**Expected behavior**
I expect the latest version of the controller and to get the ability to use all latest features

**Config files, and API responses**
creating cloudmap based service discovery was failing

**Additional context**

**Comment by smmallu** [comment]
I am working on a related item, I can update these,Please assign  to me @shubharao 
Alias @smmallu

**Comment by kiranmeduri** [comment]
@smmallu updated README to use aws/eks-charts (helm).
