### ISSUE TITLE
[BUG] Container 'colorapp' failed to be started in the pod

### ISSUE THREAD

**Issue by XiaoYangZhu** [aws/aws-app-mesh-examples#231]
_**Important note on security disclosures**: If you think you’ve found a potential security issue, please do not post it in the Issues.  Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com)._

**Describe the bug**
In tutorial of "howto-k8s-cloudmap", after the execution of './deploy.sh', we got the resource information as below:
![image](https://user-images.githubusercontent.com/24489117/69437508-69c85b00-0d7e-11ea-9ffd-e485e673551b.png)

After drilling down into the PoD level, we got:
$ kubectl describe pod/colorapp-blue-58798f666b-qxfkh -n howto-k8s-cloudmap
![image](https://user-images.githubusercontent.com/24489117/69437670-b6ac3180-0d7e-11ea-9188-3773a5415227.png)

After drilling down into the container level, we got:
![image](https://user-images.githubusercontent.com/24489117/69437940-30dcb600-0d7f-11ea-98bd-217250c4b380.png)

**Platform**
EKS 1.14

**To Reproduce**
1. Follow the steps listed in the github here.

**Expected behavior**
All the pods are created successfully.

**Config files, and API responses**
If applicable config files and responses from our API.

**Additional context**

**Comment by lavignes** [comment]
Looks like it's the same as benoitc/gunicorn#2160 ? It appears gunicorn (one of the example app dependencies) had a bug.

Can you try again by rebuilding the images for the apps?

**Comment by lanmaster53** [comment]
That won't work until it's been included in a release, right? Right now it's just a completed milestone for 20.0.1. https://github.com/benoitc/gunicorn/milestone/18

**Comment by lavignes** [comment]
@lanmaster53 thanks for the heads up! I assumed gunicorn had pushed that fix to pypi already. #232 should fix this

**Comment by XiaoYangZhu** [comment]
some update:
I loaded the latest code and tried again so it looks good now as:

![image](https://user-images.githubusercontent.com/24489117/69480215-86c56280-0e40-11ea-8d30-e3bb5a5fd84f.png)

however, there is no any service registered in the name space "howto-k8s-cloudmap.pvt.aws.local" of cloudmap, as shown below:

![image](https://user-images.githubusercontent.com/24489117/69480236-ad839900-0e40-11ea-92a0-99b8beee8448.png)

**Comment by efe-selcuk** [comment]
@XiaoYangZhu could you cut a separate issue for this cloudmap issue so we can separate it from the original problem? I'll start looking at this.

**Comment by kiranmeduri** [comment]
@XiaoYangZhu thanks for reporting this. 

Can your provide following information.

1. App Mesh controller version (should be >v0.1.2 for Cloud Map to work)
```
kubectl get deployment -n appmesh-system appmesh-controller -o json  | jq ".spec.template.spec.containers[].image"
```
2. App Mesh controller logs 
```
kubectl logs -n appmesh-system appmesh-controller-<id>
```
