### ISSUE TITLE
[BUG] curl: (6) Could not resolve host: front.howto-k8s-http-headers.svc.cluster.local

### ISSUE THREAD

**Issue by pksinghus** [aws/aws-app-mesh-examples#238]
**Describe the bug**
After deploying the app example https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-k8s-http-headers when I make a curl request to front.howto-k8s-http-headers.svc.cluster.local I get a "Could not resolve host" error.

**Platform**
EKS

**To Reproduce**
1. Go to the directory aws-app-mesh-examples/walkthroughs/howto-k8s-http-headers
2. run deploy.sh
3. run a curler pod ```kubectl -n howto-k8s-http-headers run -it curler --image=tutum/curl /bin/bash```
run curl ```curl front.howto-k8s-http-headers.svc.cluster.local:8080/;echo;```
try different variations ```curl -H "color_header: red" front.howto-k8s-http-headers.svc.cluster.local:8080/; echo;```
4. 80% of the times you get an error - "Could not resolve host"

**Expected behavior**
The hostname should resolve and you should get back a string, "yellow", "red", etc.

**Additional context**
App mesh controller v0.3.0 installed using https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/v0.3.0/scripts/deploy.sh
App mesh inject v0.3.0 installed using https://github.com/aws/aws-app-mesh-inject/blob/v0.3.0/scripts/install.sh

**Comment by Y0Username** [comment]
Hey @pksinghus, are you still seeing this issue: `80% of the times you get an error - "Could not resolve host"`?

**Comment by pksinghus** [comment]
@Y0Username I believe this may not be specific to App Mesh. This happens even without App Mesh. So, this ticket may be invalid.
