### ISSUE TITLE
[BUG] Examples/Walkthroughs will not work with AWS CLI version 2.

### ISSUE THREAD

**Issue by shwetasahuit** [aws/aws-app-mesh-examples#260]
**Describe the bug**
Our example uses aws ecr get-login for authentication. However in the AWS CLI version 2 aws ecr get-login is deprecated and is replaced with the command aws aws ecr get-login-password command. Hence the examples will fail if run on aws cli version 2.

**Platform**
All.

**Additional context**
The examples will continue to run using aws cli version 1.
Refer [here](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-ecr-get-login) for more details.

**Comment by bcelenza** [comment]
Fixed by #312.
