### ISSUE TITLE
[BUG]awscli.yaml jobs are created but not getting completed

### ISSUE THREAD

**Issue by sanatan90** [aws/aws-app-mesh-examples#266]
_**Important note on security disclosures**: If you think you’ve found a potential security issue, please do not post it in the Issues.  Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com)._

**Describe the bug**
Doc Link: https://aws.amazon.com/blogs/compute/learning-aws-app-mesh/
I am following EKS platform instruction to deploy example djapp and while creating jobs using awscli.yaml file using the command 
```
kubectl apply -f awscli.yaml
```
, jobs got created but it's never getting completed. Unable to debug the issue.

**Platform**
EKS

**To Reproduce**
Follow these steps in the below doc
Doc Link: https://aws.amazon.com/blogs/compute/learning-aws-app-mesh/

**Comment by kiranmeduri** [comment]
@geremyCohen can you take a look at this and update the documentation accordingly. Thanks

**Comment by fawadkhaliq** [comment]
Not sure if @geremyCohen is looking at this. @jlbutler would you be able to help here?

**Comment by fawadkhaliq** [comment]
@jlbutler will be picking it up

**Comment by jlbutler** [comment]
We came to a decision on this that we won't fix the linked walkthrough as it's written. At this point it's deprecated and we have better docs, blogs, and examples. Leaving this issue open until we land the solution, which will be an update on the blog from last year to link to something more current.

**Comment by jlbutler** [comment]
The upstream blog has been updated in place with a link to this repo (and specifically the getting started tutorial with djapp). We don't intend to support that previous workflow, and so closing this issue out as resolved. Thanks for calling it out!
