### ISSUE TITLE
[BUG] howto-k8s-fargate walkthrough is not working

### ISSUE THREAD

**Issue by nbrandaleone** [aws/aws-app-mesh-examples#295]
_**Important note on security disclosures**: If you think you’ve found a potential security issue, please do not post it in the Issues.  Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com)._

**Describe the bug**
The "walkthroughs/howto-k8s-fargate/deploy.sh" file has a check_k8s_virtualrouter() function, which is checked if the user opts for the "v1beta2" manifest.  The current version of the appmesh controller (0.5) will fail during this check.However, this manifest version is clearly shown in the README documentation.
`eksctl create cluster -f v1beta2/clusterconfig.yaml`

I recommend that the README be adjusted to refer to the v1beta1 so that the walthough will work with default settings and tooling.

**Platform**
EKS/Fargate

**To Reproduce**

**Expected behavior**

**Config files, and API responses**
If applicable config files and responses from our API.

**Additional context**

**Comment by fawadkhaliq** [comment]
hi @nbrandaleone , thanks for checking in this. We're in the process of adding v1beta2 support for App Mesh controller. Currently, you will see v1beta1 and v1beta2 both in howto-k8s-fargate example. To use v1beta1 example, please pass v1beta1 as an argument to the deploy.sh script: `./deploy.sh v1beta1`

If that does not work or you see any issues, please don't hesitate to report back. Thanks!

**Comment by efe-selcuk** [comment]
Let's make v1beta1 the default for now since v1beta2 isn't the default consumable version.

**Comment by fawadkhaliq** [comment]
Defaults have been fixed in the issue https://github.com/aws/aws-app-mesh-examples/pull/296
