### ISSUE TITLE
docker images for djapp for non-eks clusters

### ISSUE THREAD

**Issue by rajatjindal** [aws/aws-app-mesh-examples#306]
**Describe the bug**

Following the tutorial at https://aws.amazon.com/blogs/compute/learning-aws-app-mesh/ for our cluster deployed on AWS (non EKS), the docker images are not available.

**Platform**
Kubernetes 1.16.x deployed on EC2 using kops

**To Reproduce**
1. Follow steps on https://aws.amazon.com/blogs/compute/learning-aws-app-mesh/ to run through dj-app example
2. Expected test deployments to work, but they failed when pulling docker images.
3. See error: Back-off pulling image "672518094988.dkr.ecr.us-west-2.amazonaws.com/awscli:v9"

**Expected behavior**
One should be able to run through the example on a standalone Kubernetes cluster

**Comment by rajatjindal** [comment]
1. I tried searching on different forums, dockerhub for those images, but they are not available. 
2. I did verified my nodes have appsmesh:* permissions. (that is the only permission our nodes have). 
3. I tried looking for Dockerfiles of the services as well, but could not find them in this repo or anywhere else. 

any pointers will be very helpful.

thanks

**Comment by fawadkhaliq** [comment]
Hi @rajatjindal, it seems your cluster is missing ECR read permissions. You will need to add these permission to your cluster nodes. You could do this by adding the following policy to your node IAM roles: `arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly` or 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:DescribeRepositories",
                "ecr:ListImages",
                "ecr:DescribeImages",
                "ecr:BatchGetImage",
                "ecr:GetLifecyclePolicy",
                "ecr:GetLifecyclePolicyPreview",
                "ecr:ListTagsForResource",
                "ecr:DescribeImageScanFindings"
            ],
            "Resource": "*"
        }
    ]
}
```

Please let us know if that resolves the issue for you. Thank you!

**Comment by fawadkhaliq** [comment]
The issue was related to missing IAM permissions. @rajatjindal if there's anything else we can help with, pls feel free to open a new issue
