### ISSUE TITLE
[documentation] EKS base walkthrough doesn't work with eks/appmesh-controller v1.0.0

### ISSUE THREAD

**Issue by motzyball** [aws/aws-app-mesh-examples#307]
I was able to successfully install the appmesh-controller via:
```
$ helm upgrade -i appmesh-controller eks/appmesh-controller --namespace appmesh-system
Release "appmesh-controller" does not exist. Installing it now.
NAME: appmesh-controller
LAST DEPLOYED: Fri Jun 19 10:28:04 2020
NAMESPACE: appmesh-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
AWS App Mesh controller installed!
```

But when I try to follow the next step to install the appmesh-inject, I get an error:
```
$ helm upgrade -i appmesh-inject eks/appmesh-inject --namespace appmesh-system --set mesh.create=true --set mesh.name=in-motion-mesh-dev
Release "appmesh-inject" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Mesh" in version "appmesh.k8s.aws/v1beta1"
```

I noticed that the helm chart for appmesh-inject says: `Note: Users of AppMesh controller v1.0.0+ shouldn't install this inject chart. The sidecar injection functionality is already included in the controller itself.` but now I have no idea how to create the mesh. Is there an updated next step for 1.0.0?

**Comment by fawadkhaliq** [comment]
Hi @motzyball, thanks for reporting the issue. We're working on fixing the base install guide. In the meantime, if you would like to play with the v1.0.0, please the guide and example here [1]. The guide should be fixed today

[1] https://docs.aws.amazon.com/eks/latest/userguide/mesh-k8s-integration.html

**Comment by motzyball** [comment]
Thank you for the quickly reply @fawadkhaliq! Does your use of the word 'play' indicate that v1.0.0 is not ready for production use?

**Comment by fawadkhaliq** [comment]
> Thank you for the quickly reply @fawadkhaliq! Does your use of the word 'play' indicate that v1.0.0 is not ready for production use?

Apologies for the poor choice of words and confusion - I'll improve wording. v1.0.0 is ready for production use

**Comment by fawadkhaliq** [comment]
@motzyball the EKS base walkthrough has been updated. Thank you for reporting the issue
