### ISSUE TITLE
Update k8s cross cluster example?

### ISSUE THREAD

**Issue by benpettman** [aws/aws-app-mesh-examples#314]
I am using the latest controller and cant get the k8s cross cluster example to work with the latest controller and crds.

Could you update the example to the latest controller?

**Comment by jlbutler** [comment]
@benpettman Sorry for the troubles.

That walkthrough should bring you to the base install instructions, resulting in installation of the latest stable controller:  
https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/eks/base.md#install-app-mesh--kubernetes-components

What version did you install? You can check with:

kubectl get deployment -n appmesh-system appmesh-controller -o json | jq -r ".spec.template.spec.containers[].image" | cut -f2 -d ':'|tail -n1

**Comment by benpettman** [comment]
I don’t need help getting the latest controller as I have that. 

Your example doesn’t work with the latest controller, so wondering if you can update it to work with the latest?

**Comment by bcelenza** [comment]
Yeah, the issue here is that the example for cross-cluster has not been updated for the v1 controller: https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-k8s-cross-cluster. It's still using the v1beta1 CRDs and annotations.

**Comment by fawadkhaliq** [comment]
hi @benpettman, cross cluster example is planned to be updated. We will be creating PR soon. Stay tuned

**Comment by fawadkhaliq** [comment]
Cross cluster example has been updated: https://github.com/aws/aws-app-mesh-examples/pull/316
