### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dazza65** [aws/aws-app-mesh-examples#342]
**Describe the bug**
Two of the six services fail to start due to there not being enough ENIs available to run all of the tasks.

The following error message is reported in the Events tab of the ECS Service that fails to start:

```service appmesh-dev-ecs-colorapp-TcpEchoService-14M0PCTB9QFKJ was unable to place a task because no container instance met all of its requirements. The closest matching container-instance acf43593-6b86-4838-86e5-46d896fdc8b3 encountered error "RESOURCE:ENI". For more information, see the Troubleshooting section.```

**Platform**
ECS, EC2.

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow the steps detailed in the colorapp walkthrough page https://github.com/aws/aws-app-mesh-examples/tree/master/examples/apps/colorapp#review-1
2. Monitor the CloudFormation Events tab for the final stack creation for the ECS application deployment step - ```./examples/apps/colorapp/ecs/ecs-colorapp.sh``` until it attempts to create the ColorGatewayService.
3. Go to the ECS console and select a service from the cluster that has failed to start.
4. Select the Events tab and view the resulting error message.

**Expected behaviour**
All six ECS services should start and be in a stable state.

**Additional context**
Enabling ENI trunking in the ECS account settings and changing the instance types to an ENI trunking compatible one E.g. c5.large resolves the problem

**Comment by Y0Username** [comment]
This looks like your ECS cluster does not have enough capacity to provision these containers.
Add more ECS instances to the cluster to solve the problem.

**Comment by jamsajones** [comment]
Looks like @Y0Username provided a solution. Please fee free to re-open if the solution did not resolver your problem.
