### ISSUE TITLE
k8s ingress example not working 

### ISSUE THREAD

**Issue by ntorba** [aws/aws-app-mesh-examples#347]
*SECURITY NOTICE: If you think you’ve found a potential security issue, please do not post it in the Issues. Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com).*

**Summary**
What are you observing that doesn't seem right?

While following the [app mesh k8s ingress example](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-k8s-ingress-gateway), I can't get the right results. 

**Steps to Reproduce**
What are the steps you can take to reproduce this issue?

Follow the tutorial steps. At the command `kubectl get virtualgateway -n howto-k8s-ingress-gateway`, the attribute for ARN is empty. 

Also, after I ran deploy, my load balancer status was <pending> until I added the annotations 
```
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
service.beta.kubernetes.io/aws-load-balancer-internal: 10.0.0.0/8
```
to my load balancer service. 

The logs in my pod show this message repeatedly:
```bash
[2020-09-21 19:38:04.680][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:93] StreamAggregatedResources gRPC config stream closed: 3, Resource not found: mesh/howto-k8s-ingress-gateway/virtualGateway/ingress-gw_howto-k8s-ingress-gateway.
```

Also, the mesh I am trying to build never completes. I do not see it created in aws console or when running the command `aws appmesh list-meshes`

**Are you currently working around this issue?**
How are you currently solving this problem?

Have not found a solution

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by achevuru** [comment]
@ntorba Closing the issue for now. Please feel free to re-open if you are still running in to any issues.
