### ISSUE TITLE
howto-ecs-basics example always fails at step 2 ./deploy.sh deploy 2-meshify

### ISSUE THREAD

**Issue by lubingfeng** [aws/aws-app-mesh-examples#351]
**Describe the bug**
I am trying the sample https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-ecs-basics. 

I was able to complete deployment of servicedeployment and see it on cloudwatch service map. However when I tried 
% ./deploy.sh deploy 2-meshify

It took very long time (**~30 minutes**) and then I got a message saying 
```
Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
aws cloudformation describe-stack-events --stack-name appmesh-howto-ecs-basics
```

If tried again, I kept getting the following message: 

```
deploy app using stage 2-meshify
Deploying stack appmesh-howto-ecs-basics, this may take a few minutes...
An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-west-2:890276997447:stack/appmesh-howto-ecs-basics/c27ce4b0-0dc7-11eb-92f2-06b6cdf5c503 is in UPDATE_IN_PROGRESS state and can not be updated.
```

What should I do next? 

**Platform**
ECS, EC.

**To Reproduce**
Follow the steps in the sample: https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-ecs-basics

**Expected behavior**
It should work like a charm and should take no more than 5 minutes to update the cloudformation stack. 

**Config files, and API responses**
If applicable config files and responses from our API.

**Additional context**

**Comment by lubingfeng** [comment]
Please close the issue. 

I got ENVOY_IMAGE environment variable is not set to App Mesh Envoy, see https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html
export ENVOY_IMAGE=...

**Comment by jamsajones** [comment]
Closing per lubingfeng
