### ISSUE TITLE
[BUG] Hostname set to AWS_XRAY_DAEMON_ADDRESS makes Envoy throw Error and ECS service fail

### ISSUE THREAD

**Issue by shaileshgupta2k** [aws/aws-app-mesh-examples#393]
_**Important note on security disclosures**: If you think you’ve found a potential security issue, please do not post it in the Issues.  Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com)._

**Describe the bug**
Customer try to use a remote X-Ray daemon with AppMesh, it worked well to set IP address to AWS_XRAY_DAEMON_ADDRESS.

However, a hostname is set to AWS_XRAY_DAEMON_ADDRESS, then appmesh-envoy container reported the following error.

```
[2021-02-11 00:52:19.284][1][warning][config] [source/common/config/grpc_subscription_impl.cc:107] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) lds_ingress_0.0.0.0_15000: malformed IP address: xraydaemon.default.svc.cluster.local:2000
```
And ECS service failed because of ELB health check failure.
I confirmed this issue happened with `aws-appmesh-envoy:v1.16.1.0-prod`

**Platform**
ECS

**To Reproduce**
Steps to reproduce this issue:

1. Setup colorapp using the following sample.
https://github.com/aws/aws-app-mesh-examples/tree/master/examples/apps/colorapp

2. Prepare xray daemon.
For example, use attached xray-daemon.sh and xray-daemon.yaml to setup xray-daemon fargate in the cluster.
In my example, xraydaemon.default.svc.cluster.local is DNS name to use xray daemon.

3. Edit taskdef to use the xray daemon setup in the previous step.
Set like the following change.

```
$ git diff examples/apps/colorapp/ecs/envoy-container.json 
diff --git a/examples/apps/colorapp/ecs/envoy-container.json b/examples/apps/colorapp/ecs/envoy-container.json
index 91b84b3..b4cf290 100644
--- a/examples/apps/colorapp/ecs/envoy-container.json
+++ b/examples/apps/colorapp/ecs/envoy-container.json
@@ -47,6 +47,10 @@
     {
       "name": "ENABLE_ENVOY_STATS_TAGS",
       "value": "1"
+    },
+    {
+      "name": "AWS_XRAY_DAEMON_ADDRESS",
+      "value": "xraydaemon.default.svc.cluster.local:2000"
     }
   ],
   "logConfiguration": {
```
4. After editing the above taskdef, then deploy the app again.
You will see the following error in appmesh-envoy's log:
```
[2021-02-11 00:52:19.284][1][warning][config] [source/common/config/grpc_subscription_impl.cc:107] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) lds_ingress_0.0.0.0_15000: malformed IP address: xraydaemon.default.svc.cluster.local:2000
```
(I attached appmesh-envoy.gz exported from my test.)

5. When you check ColorGatewayService , the task doesn't start well because of the following health check failure.
ECS event log
```
service case2175608193tt-ecs-colorapp-ColorGatewayService-n4VY1e9zpiC7 (instance 10.0.73.147) (port 9080) is unhealthy in target-group case2175608193tt-web due to (reason Health checks failed)
```

**Workaround**
1. Use IP address for AWS_XRAY_DAEMON_ADDRESS .
2. Use sidecar container like the example.

**Expected behavior**
Check appmesh-envoy container can accept to use a hostname for AWS_XRAY_DAEMON_ADDRESS or not? If it should work, please consider to fix the issue.

**Config files, and API responses**
No files attached.

**Comment by AKBarcenas** [comment]
Closing this issue in favor of this one on our roadmap: https://github.com/aws/aws-app-mesh-roadmap/issues/319
