### ISSUE TITLE
[BUG] The use of front app (custom image - FRONT_APP_IMAGE) is not well explained in the documentation for eks

### ISSUE THREAD

**Issue by jayeshnazre** [aws/aws-app-mesh-examples#404]
**Describe the bug**
The use of front app (custom image - FRONT_APP_IMAGE) is not well explained in the documentation for eks. Looking at the custom python code: [https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-k8s-alb/feapp](url)
**Platform**
EKS

**Expected behavior**
Please provide a clear use of the front-end service and whether its a scalable approach. Also how it comes into play when VirtualGateway is used. 

**Additional context**
It feels like the front-end service is making a REST call to the back-end color service and seems to behave like a proxy (so why is there no proxy implementation (similar to nginx) used as the base image in Dockerfile instead to make this scalable?)

**Comment by jayeshnazre** [comment]
@cgchinmay 
Thanks for assigning this to yourself. I am finding very limited documentation of using ALB with AppMesh in EKS (I am using ALB controller and Appmesh controller inside EKS). Especially when it comes to the new CRD - VirtualGateway. This example site is the closest I have to connecting the pieces together. Hence I wanted to post this documentation question for everyone's benefit (Specifically Moi :) )

**Comment by cgchinmay** [comment]
The purpose of the walkthrough is to demonstrate use of ALB and how it routes traffic to backend service. The feapp could have been any collection of pods (service) which does some work and to which ALB routes requests. It could have also been a Gateway as pointed by below links. The walkthrough does point to some ALB links but I find that they are broken. Will fix it. 

Here is useful documentation on how ALB controller works with AppMesh and EKS
https://aws.amazon.com/blogs/containers/app-mesh-integration-with-aws-alb-ingress-controller/
https://aws.amazon.com/blogs/opensource/kubernetes-ingress-aws-alb-ingress-controller/

> whether its a scalable approach

Could you explain on this part ? Are you asking how many replicas of feapp are supported by the ALB ?

**Comment by jayeshnazre** [comment]
@cgchinmay 
Thanks for responding. I am glad you provided the first link [https://aws.amazon.com/blogs/containers/app-mesh-integration-with-aws-alb-ingress-controller/](url) actually I was looking at that as well. Maybe its just me trying to connect the dots. So the source code link in that blog is incorrect in Step 4: The below link is not working - 
https://raw.githubusercontent.com/aws/aws-app-mesh-controller-for-k8s/master/examples/color.yaml

So I did some goggling (if that's a word) :) and found the below github repo for the blog 

https://github.com/aws/aws-app-mesh-examples/tree/master/examples

I then started looking at the Gateway code (Which based on my understanding has nothing to do with the CRD VirtualGateway). With my limited knowledge and what I understand from the blog https://aws.amazon.com/blogs/containers/app-mesh-integration-with-aws-alb-ingress-controller/

It seems like the code has defined a VirtualNode that is pointing to a backend Service (the K8s service - colorgateway) and the AppMesh VirtualService (colorteller and tcpecho).  (CloudFormation code for that - https://github.com/aws/aws-app-mesh-examples/blob/master/examples/apps/colorapp/servicemesh/appmesh-colorapp.yaml

If I trace the breadcrumbs that K8s service colorgateway looks at a deployment which is using the Docker image defined in the env variable: COLOR_GATEWAY_IMAGE, which is using the custom image build for the gateway via the code - https://github.com/aws/aws-app-mesh-examples/tree/master/examples/apps/colorapp/src/gateway

**Can you confirm that I have understood what that blog is doing correctly so far?**

Assuming I am following the breadcrumbs correctly 
Are both your examples as well as that blog example (which is using go instead of python) saying that this is the approach we need to take for real-world production architecture (which is to built your own custom Gateway image) - that seems a bit error-prone when we are looking for a supported image that will do that for us (like how envoy image is provided and supported for VirtualGateway). 

Finally, If VirtualGateway CRD is a way to open up outside traffic to AppMesh, where is an example of opening VIrtualGateway via ALB, there is an example to do that via NLB in the links below

https://docs.aws.amazon.com/app-mesh/latest/userguide/getting-started-kubernetes.html
https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/howto-k8s-ingress-gateway/v1beta2/manifest.yaml.template

W.r.t. scalable approach, I meant not the scaling of pod way but scalable in the sense best architecture practice of using a custom image to define your gateway.

**Comment by cgchinmay** [comment]
> Can you confirm that I have understood what that blog is doing correctly so far?

Yes. The example just uses gateway as the name but its a virtual node

> If VirtualGateway CRD is a way to open up outside traffic to AppMesh, where is an example of opening VIrtualGateway via ALB, there is an example to do that via NLB in the links below

VGW and ALB are conceptually same thing, they both do routing based on prefix/path. 
https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/howto-k8s-ingress-gateway/v1beta2/manifest.yaml.template
This example exposes VGW via nlb as the Service type supports only nlb and classic load balancer. Check this: https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html. If you wanted to use an ALB then you would create a resource of type ingress instead. 

> best architecture practice of using a custom image to define your gateway.

It depends on your use case. The first example is actually routing traffic from ALB to virtual node which points to a deployment. So it has a custom image with the routing logic. If you had a VGW, you would specify the routing rules using Gateway Routes instead.

**Comment by jayeshnazre** [comment]
@cgchinmay 
Thanks for responding. So basically I wanted to go down the path of ALB to see if I can use WAF which I believe NLB does not natively support (yes there are hacks of putting NLB in front of ALB etc. but no straight support)

W.r.t the link - https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/howto-k8s-ingress-gateway/v1beta2/manifest.yaml.template

I used that sample example as well but it creates a NLB and as mentioned before I was trying to use ALB for WAF not necessarily the path based routing that as you righly pointed out can be done via GatewayRoute. So this is what I think works for me but I wanted your input on this

In the example - https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/howto-k8s-ingress-gateway/v1beta2/manifest.yaml.template

The VirtualGateway points to pods labeled - app: ingress-gw (which is basically the envoy image ${ENVOY_IMAGE} container created by the deployment)

I know for exposing Ingress via ALB I need ALB load balancer controller deployed in my EKS, so I deployed one and then in my ingress YAML I used 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingressalb1
  namespace: ${APP_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ingress-gw
              servicePort: 80      

The ingress points to my envoy proxy service  ingress-gw and that service is a typical Loadbalancer type service with no nlb annotation - YAML below

apiVersion: v1
kind: Service
metadata:
  name: ingress-gw
  namespace: ${APP_NAMESPACE}
spec:
  ports:
    - port: 80
      targetPort: 8088
      name: http
  selector:
    app: ingress-gw

With that I have my ALB via Ingress pointing to my envoy container and that way I get entry into the App Mesh.

Can you confirm that with this working that the App Mesh traffic (east-west) is correctly configured to allow external (north-south) traffic to access my App Mesh and all the traffic flow control in the AWS App Mesh like (mTLS between service to service communication etc.) will work?

**Comment by cgchinmay** [comment]
@jayeshnazre apologies for delayed response 
Looks like it should work but you need try this setup with the above example and verify that you are getting the desired output. We also have an mTLS walkthrough: [mTLS](https://github.com/aws/aws-app-mesh-examples/tree/main/walkthroughs/howto-k8s-mtls-file-based).

**Comment by cgchinmay** [comment]
@jayeshnazre Closing this issue/thread, as the original FRONT_APP_IMAGE related question has been answered.
