### ISSUE TITLE
[BUG] Docker build: "go.mod file not found"

### ISSUE THREAD

**Issue by alexbrjo** [aws/aws-app-mesh-examples#411]
**Describe the bug**

Color teller in the `howto-mutual-tls-file-provided` walkthrough is not building.

```
 > [builder 3/3] RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo -o /app .:
#8 0.449 go: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

**Platform**
EKS, ECS, EC2, etc.

**To Reproduce**

Perform [the howto-mutual-tls-file-provided walkthrough](https://github.com/aws/aws-app-mesh-examples/tree/main/walkthroughs/howto-mutual-tls-file-provided) up to the `./src/colorteller/deploy.sh` step

**Expected behavior**
Image should build

**Config files, and API responses**
If applicable config files and responses from our API.

**Additional context**
Looks like Go had a release in the last month and the image tag we're using may now be pointing to a newer image. [Go 1.16 release notes](https://golang.org/doc/go1.16#go-command)

**Comment by alexbrjo** [comment]
Work around: use the `golang-1.15-buster` image instead of `golang:1-buster` [here](https://github.com/aws/aws-app-mesh-examples/blob/main/walkthroughs/howto-mutual-tls-file-provided/src/colorteller/Dockerfile#L1).

**Comment by suniltheta** [comment]
With https://github.com/aws/aws-app-mesh-examples/pull/456 update this is not applicable anymore. So closing this issue.
