### ISSUE TITLE
[BUG]howto-ecs-basics Chapter 2: Meshify! does not work

### ISSUE THREAD

**Issue by gavindoudou** [aws/aws-app-mesh-examples#413]
_**Important note on security disclosures**: If you think you’ve found a potential security issue, please do not post it in the Issues.  Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com)._

**Describe the bug**
I am following the instruction here: https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-ecs-basics#chapter-2-meshify but I got the error in ECS consle:
```
ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve ecr registry auth: service call has been retried 5 time(s): RequestError: send request failed caused by: Post https://api.ecr....
```
![image](https://user-images.githubusercontent.com/31523962/118314503-16cdf080-b4a9-11eb-9de6-b279951233a8.png)
Could you please take a look? Thanks!
**Platform**
ECS

**To Reproduce**
1. Go to https://github.com/aws/aws-app-mesh-examples/tree/main/walkthroughs/howto-ecs-basics
2. Follow Prerequeistes, bootstrap and then go to Chapter 2
3. See error in ECS console

**Expected behavior**
I ran this tutorial before and it worked. The expected behavior is that there will be 6 task running in that cluster. The error seems to be a Fargate version problem. I downgrade to Fargate 1.3 but still does not work. 

**Additional context**

**Comment by lavignes** [comment]
@gavindoudou looks like you just closed this issue. Was this a separate issue and not a bug? Just want to document why we're closing it in case someone runs into this issue when searching.

**Comment by gavindoudou** [comment]
It's my mistake, not a bug from your side.Thanks for the help.
