### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ssccio** [aws/aws-app-mesh-examples#559]
_**Important note on security disclosures**: If you think you’ve found a potential security issue, please do not post it in the Issues.  Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com)._

**Describe the bug**
The microservices appear to be missing from the ecs-canary-deployments-pipeline example.

**Platform**
ECS

**To Reproduce**
1. cd blogs/ecs-canary-deployments-pipeline
2. make create-shared-cloudformation-stack

./setup/scripts/create_shared_cloudformation_stack.sh
Starting the zipping activity of the microservices code
./setup/scripts/create_shared_cloudformation_stack.sh: line 17: cd: setup/scripts/../../microservices/yelb-ui: No such file or directory
./setup/scripts/create_shared_cloudformation_stack.sh: line 18: cd: setup/scripts/../../microservices/yelb-db: No such file or directory
./setup/scripts/create_shared_cloudformation_stack.sh: line 19: cd: setup/scripts/../../microservices/yelb-appserver: No such file or directory
./setup/scripts/create_shared_cloudformation_stack.sh: line 20: cd: setup/scripts/../../microservices/yelb-redisserver: No such file or directory

**Expected behavior**
Microservices to be present.

**Comment by ysdongAmazon** [comment]
Hello,
Will reproduce the example and get back to you soon. Thanks

**Comment by BennettJames** [comment]
It appears that there may have been some[ missing files from the eks demo](https://github.com/aws/aws-app-mesh-examples/tree/main/blogs/eks-canary-deployments-pipeline/microservices) that need to either be copied or correctly referred to from the ecs demo.

We'll have to straighten out the files and make sure both work as expected.

**Comment by ysdongAmazon** [comment]
You are right, you can follow the steps of this blob to reproduce:
The walkthrough for this tutorial: https://aws.amazon.com/cn/blogs/containers/create-a-pipeline-with-canary-deployments-for-amazon-ecs-using-aws-app-mesh/

**Comment by ysdongAmazon** [comment]
Confirmed the right repo
