### ISSUE TITLE
Other partner integrations

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-examples#8]

**Comment by vikramraman** [comment]
@jamsajones How can other partners integrate with AWS app mesh? I work on monitoring (metrics/tracing) at [Wavefront by VMware](https://www.wavefront.com/). We are very interested in learning more about how we can provide a native integration with app mesh. Please let us know. Thanks!

**Comment by jamsajones** [comment]
@vikramraman, we are happy to integrate with new partners. You can reach out to me directly at jsstraub at amazon dot com and I will put you in contact with our partner team to get things started.

**Comment by PettitWesley** [comment]
The OpenTelemetry integration will eventually cover this
