### ISSUE TITLE
unable to download images envoy and proxy image

### ISSUE THREAD

**Issue by daparthi001** [aws/aws-app-mesh-examples#86]
**Describe the bug**

**Platform**
EKS, ECS, EC2, etc.

**To Reproduce**

**Expected behavior**

**Config files, and API responses**
If applicable config files and responses from our API.

**Additional context**
App Mesh Envoy container image: 111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.8.0.2-beta
App Mesh proxy route manager: 111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:latest

**Comment by bcelenza** [comment]
Hi @daparthi001, can you provide more information on where the download is failing? Are you pulling the image locally or through ECS/EKS? Could you provide the log or error you are seeing?

**Comment by daparthi001** [comment]
I am trying to pull images to ec2 with Kubernetes,Are you able to pull images from that ecr ?Do you know if I can pull from any another location ?
error:
no basic auth credentials

**Comment by bcelenza** [comment]
I see, so it sounds like you're running Kubernetes directly on EC2? A few follow-up questions if thats the case:

1. What version of Kubernetes are you running?
2. Do your worker nodes have permissions to pull from ECR as [described here](https://kubernetes.io/docs/concepts/containers/images/#using-aws-ec2-container-registry)?

**Comment by daparthi001** [comment]
My Worker node doesn't have access to this ecr ,but configured to access my ecr

**Comment by daparthi001** [comment]
I am able to push/pull to my own ecr,but not able to pull from 111345817488.dkr.ecr.us-west-2
$ docker push 431450989016.dkr.ecr.us-east-1.amazonaws.com/color_teller:latest
The push refers to repository [431450989016.dkr.ecr.us-east-1.amazonaws.com/color_teller]
f6bdbdcdc08d: Pushed
latest: digest: sha256:ce7911c463ba15ccade7d6bf18a352df7028c864102ebf7228b8525018608249 size: 528
$ docker pull 111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.8.0.2-beta
Error response from daemon: Get https://111345817488.dkr.ecr.us-west-2.amazonaws.com/v2/aws-appmesh-envoy/manifests/v1.8.0.2-beta: no basic auth credentials

**Comment by bcelenza** [comment]
This is a little bit of a guess, but I think you may not have a valid auth token for the `111345817488` registry in us-west-2. Even though the login command succeeded, you may only have a valid token assigned to your own registry (`431450989016`).

See [this reference](https://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors-docker.html#error-403). Although it mentions pushing to ECR, the same issue would apply for a pull.

Can you try the following alternate login to see if it helps?

`$(aws ecr get-login --no-include-email --region us-west-2 --registry-ids 111345817488)`
