### ISSUE TITLE
Switch to wildcard DNS entry for service names in example

### ISSUE THREAD

**Issue by dastbe** [aws/aws-app-mesh-examples#89]
Because we still require *some* DNS entry for applications to resolve *some* IP before it will make a request that envoy can proxy, the examples end up duplicating names across service discovery and router service names/backends. This leads to confusion because it's implied there's some coordination between the two when there isn't.

We can fix our example apps by creating a private hosted zone for "#{meshName}.appmesh" with a wildcard entry to any IP. VirtualRouters will register on "colorgateway.#{meshName}.appmesh" and "colorteller.#{meshName}.appmesh" and the actual VNode service discovery can use existing kubedns/CloudMap names. I would expect this would be how we recommend customers configure things as well until we have a better solution for the DNS hole.

**Comment by kiranmeduri** [comment]
I agree, made use of this pattern in [howto-ecs-basics](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-ecs-basics) walkthrough

https://github.com/aws/aws-app-mesh-examples/blob/bdd7323fb268f0610d7582a3775f58c1c212990c/walkthroughs/howto-ecs-basics/deploy/2-meshify.yaml#L290

**Comment by kiranmeduri** [comment]
Changing other examples may be not necessary, closing this.
